#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DBChooserApp.Android.Resource", IsApplication=true)]

namespace DBChooserApp.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f06002b
			public const int actionBarBackground = 2131099691;
			
			// aapt resource value: 0x7f06002a
			public const int actionBarHighlight = 2131099690;
			
			// aapt resource value: 0x7f06002d
			public const int actionModeBackground = 2131099693;
			
			// aapt resource value: 0x7f06002c
			public const int actionModeHighlight = 2131099692;
			
			// aapt resource value: 0x7f060045
			public const int album_list_cover_image_frame = 2131099717;
			
			// aapt resource value: 0x7f060047
			public const int barDark = 2131099719;
			
			// aapt resource value: 0x7f060048
			public const int barDarkBorder = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int barLight = 2131099721;
			
			// aapt resource value: 0x7f06004a
			public const int barLightBorder = 2131099722;
			
			// aapt resource value: 0x7f06002f
			public const int blackBackground = 2131099695;
			
			// aapt resource value: 0x7f060002
			public const int blue = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int blueBackground = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int buttonHighlight = 2131099654;
			
			// aapt resource value: 0x7f06001f
			public const int darkBlueText = 2131099679;
			
			// aapt resource value: 0x7f06001c
			public const int darkButtonText = 2131099676;
			
			// aapt resource value: 0x7f060021
			public const int darkGrayText = 2131099681;
			
			// aapt resource value: 0x7f060005
			public const int dialogBoxTitleBackground = 2131099653;
			
			// aapt resource value: 0x7f060028
			public const int errorText = 2131099688;
			
			// aapt resource value: 0x7f060032
			public const int feature_popover_bg = 2131099698;
			
			// aapt resource value: 0x7f060031
			public const int feature_popover_border = 2131099697;
			
			// aapt resource value: 0x7f06000b
			public const int fileListMediumGrayText = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int filelistBackground = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int filelistItemFocused = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int filelistItemPressed = 2131099658;
			
			// aapt resource value: 0x7f060034
			public const int folderTitleBackground = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int folderTitleBackgroundBorder = 2131099701;
			
			// aapt resource value: 0x7f06000e
			public const int galleryChromeBackground = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int galleryChromeTransparencyBackgroundDark = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int galleryChromeTransparencyBackgroundLight = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int galleryItemSelectedOverlay = 2131099661;
			
			// aapt resource value: 0x7f060016
			public const int grayBlueishText = 2131099670;
			
			// aapt resource value: 0x7f06001b
			public const int grayButtonText = 2131099675;
			
			// aapt resource value: 0x7f060001
			public const int green = 2131099649;
			
			// aapt resource value: 0x7f060019
			public const int greenButtonText = 2131099673;
			
			// aapt resource value: 0x7f06001d
			public const int lightBlueBackground = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int lightBlueBackground2 = 2131099678;
			
			// aapt resource value: 0x7f06000c
			public const int listEmptyText = 2131099660;
			
			// aapt resource value: 0x7f060011
			public const int localFilelistBackground = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int localListEmptyText = 2131099666;
			
			// aapt resource value: 0x7f060018
			public const int loginButtonText = 2131099672;
			
			// aapt resource value: 0x7f060015
			public const int loginText = 2131099669;
			
			// aapt resource value: 0x7f060020
			public const int mediumGrayText = 2131099680;
			
			// aapt resource value: 0x7f060029
			public const int passcodeBackgroundOverride = 2131099689;
			
			// aapt resource value: 0x7f06003e
			public const int passwordStrength1 = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int passwordStrength2 = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int passwordStrength3 = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int passwordStrength4 = 2131099713;
			
			// aapt resource value: 0x7f06003c
			public const int passwordStrengthMeterLit = 2131099708;
			
			// aapt resource value: 0x7f06003b
			public const int passwordStrengthMeterUnlit = 2131099707;
			
			// aapt resource value: 0x7f06003a
			public const int passwordStrengthText = 2131099706;
			
			// aapt resource value: 0x7f06003d
			public const int passwordStrengthUnlitPhone = 2131099709;
			
			// aapt resource value: 0x7f06002e
			public const int photoTabBackground = 2131099694;
			
			// aapt resource value: 0x7f060000
			public const int red = 2131099648;
			
			// aapt resource value: 0x7f06001a
			public const int redButtonText = 2131099674;
			
			// aapt resource value: 0x7f060017
			public const int ssLoginText = 2131099671;
			
			// aapt resource value: 0x7f060044
			public const int ss_passwordStrengthMeterLit = 2131099716;
			
			// aapt resource value: 0x7f060043
			public const int ss_passwordStrengthMeterUnlit = 2131099715;
			
			// aapt resource value: 0x7f060042
			public const int ss_passwordStrengthText = 2131099714;
			
			// aapt resource value: 0x7f060033
			public const int statusBarSeparator = 2131099699;
			
			// aapt resource value: 0x7f060014
			public const int text = 2131099668;
			
			// aapt resource value: 0x7f060007
			public const int textFieldStroke = 2131099655;
			
			// aapt resource value: 0x7f060013
			public const int textHighlight = 2131099667;
			
			// aapt resource value: 0x7f060026
			public const int titleBarText = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int titleBarTextWhite = 2131099687;
			
			// aapt resource value: 0x7f060025
			public const int tourBoxText = 2131099685;
			
			// aapt resource value: 0x7f060024
			public const int tourGrayBorder = 2131099684;
			
			// aapt resource value: 0x7f060022
			public const int tourText = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int tourTitleText = 2131099683;
			
			// aapt resource value: 0x7f060037
			public const int translucentBlackBackground = 2131099703;
			
			// aapt resource value: 0x7f060039
			public const int translucentFileListMediumGrayText = 2131099705;
			
			// aapt resource value: 0x7f060036
			public const int translucentWhiteBackground = 2131099702;
			
			// aapt resource value: 0x7f060038
			public const int translucentWhiteText = 2131099704;
			
			// aapt resource value: 0x7f060046
			public const int videoIconDetailsBackground = 2131099718;
			
			// aapt resource value: 0x7f060003
			public const int whiteBackground = 2131099651;
			
			// aapt resource value: 0x7f060030
			public const int whiteText = 2131099696;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f04000f
			public const int appStoreInterstitialMargin = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int buttonTextSize = 2130968590;
			
			// aapt resource value: 0x7f040000
			public const int dbx_action_bar_default_height = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int dbx_action_bar_icon_vertical_padding = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int dbx_action_bar_subtitle_bottom_margin = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int dbx_action_bar_subtitle_text_size = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int dbx_action_bar_subtitle_top_margin = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int dbx_action_bar_title_text_size = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int dbx_action_button_min_width = 2130968582;
			
			// aapt resource value: 0x7f04000c
			public const int dbx_dialog_min_width_major = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int dbx_dialog_min_width_minor = 2130968589;
			
			// aapt resource value: 0x7f040009
			public const int dbx_dropdownitem_icon_width = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int dbx_dropdownitem_text_padding_left = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int dbx_dropdownitem_text_padding_right = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int dbx_search_view_preferred_width = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int dbx_search_view_text_min_width = 2130968586;
			
			// aapt resource value: 0x7f040011
			public const int fileChooserButtonLeft = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int fileChooserButtonRight = 2130968594;
			
			// aapt resource value: 0x7f040010
			public const int fileChooserButtonsPadding = 2130968592;
			
			// aapt resource value: 0x7f040016
			public const int fileChooserPaddingBottom = 2130968598;
			
			// aapt resource value: 0x7f040014
			public const int fileChooserPaddingLeft = 2130968596;
			
			// aapt resource value: 0x7f040013
			public const int fileChooserPaddingRight = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int fileChooserPaddingTop = 2130968597;
			
			// aapt resource value: 0x7f040017
			public const int fileChooserTitleText = 2130968599;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_bar_light_gray_bottom = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_btn_green_disabled = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_btn_green_focused = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_btn_green_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_btn_green_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_btn_light_gray_disabled = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_btn_light_gray_focused = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_btn_light_gray_normal = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_btn_light_gray_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_button_green = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_button_light_gray = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_launcher = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_new = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int monoandroidsplash = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int tab_dropbox = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int tab_dropbox_inactive = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090010
			public const int btnDirect = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int btnLocal = 2131296273;
			
			// aapt resource value: 0x7f09000f
			public const int btnPreview = 2131296271;
			
			// aapt resource value: 0x7f09000a
			public const int dbx_bottom_bar = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int dbx_bottom_bar_cancel_button = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int dbx_bottom_bar_ok_button = 2131296268;
			
			// aapt resource value: 0x7f090009
			public const int dbx_bottom_space = 2131296265;
			
			// aapt resource value: 0x7f090001
			public const int dbx_button_bar = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int dbx_button_container = 2131296256;
			
			// aapt resource value: 0x7f090006
			public const int dbx_icon = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int dbx_install_main = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int dbx_install_sub = 2131296264;
			
			// aapt resource value: 0x7f090003
			public const int dbx_install_title = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int dbx_main_container = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int dbx_separator = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int dbx_top_space = 2131296261;
			
			// aapt resource value: 0x7f09000e
			public const int lblSubtitle = 2131296270;
			
			// aapt resource value: 0x7f09000d
			public const int lblTitle = 2131296269;
			
			// aapt resource value: 0x7f090012
			public const int lstData = 2131296274;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int dbx_max_action_buttons = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int app_store_interstitial = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int bottom_bar_light = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int bottom_buttons_light = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int list_item_entry = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int list_item_section = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f07000a
			public const int btnDirect = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int btnLocal = 2131165195;
			
			// aapt resource value: 0x7f070009
			public const int btnPreview = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int dbx_install = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int dbx_install_button_cancel = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int dbx_install_button_ok = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int dbx_install_main = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int dbx_install_sub = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int dbx_update = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int dbx_update_button_ok = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int dbx_update_main = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int dbx_update_sub = 2131165190;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int AppBaseTheme = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int AppTheme = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int BottomBar = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int BottomBarContainer = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int CommonButtonGreen = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int CommonButtonLightGray = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int Mono_Android_Theme_Splash = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int _CommonButtonBase = 2131230724;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
