#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("image.Resource", IsApplication=true)]

namespace image
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Splat.Resource.String.library_name = global::image.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f07002b
			public const int actionBarBackground = 2131165227;
			
			// aapt resource value: 0x7f07002a
			public const int actionBarHighlight = 2131165226;
			
			// aapt resource value: 0x7f07002d
			public const int actionModeBackground = 2131165229;
			
			// aapt resource value: 0x7f07002c
			public const int actionModeHighlight = 2131165228;
			
			// aapt resource value: 0x7f070045
			public const int album_list_cover_image_frame = 2131165253;
			
			// aapt resource value: 0x7f070047
			public const int barDark = 2131165255;
			
			// aapt resource value: 0x7f070048
			public const int barDarkBorder = 2131165256;
			
			// aapt resource value: 0x7f070049
			public const int barLight = 2131165257;
			
			// aapt resource value: 0x7f07004a
			public const int barLightBorder = 2131165258;
			
			// aapt resource value: 0x7f07002f
			public const int blackBackground = 2131165231;
			
			// aapt resource value: 0x7f070002
			public const int blue = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int blueBackground = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int buttonHighlight = 2131165190;
			
			// aapt resource value: 0x7f07001f
			public const int darkBlueText = 2131165215;
			
			// aapt resource value: 0x7f07001c
			public const int darkButtonText = 2131165212;
			
			// aapt resource value: 0x7f070021
			public const int darkGrayText = 2131165217;
			
			// aapt resource value: 0x7f070005
			public const int dialogBoxTitleBackground = 2131165189;
			
			// aapt resource value: 0x7f070028
			public const int errorText = 2131165224;
			
			// aapt resource value: 0x7f070032
			public const int feature_popover_bg = 2131165234;
			
			// aapt resource value: 0x7f070031
			public const int feature_popover_border = 2131165233;
			
			// aapt resource value: 0x7f07000b
			public const int fileListMediumGrayText = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int filelistBackground = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int filelistItemFocused = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int filelistItemPressed = 2131165194;
			
			// aapt resource value: 0x7f070034
			public const int folderTitleBackground = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int folderTitleBackgroundBorder = 2131165237;
			
			// aapt resource value: 0x7f07000e
			public const int galleryChromeBackground = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int galleryChromeTransparencyBackgroundDark = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int galleryChromeTransparencyBackgroundLight = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int galleryItemSelectedOverlay = 2131165197;
			
			// aapt resource value: 0x7f070016
			public const int grayBlueishText = 2131165206;
			
			// aapt resource value: 0x7f07001b
			public const int grayButtonText = 2131165211;
			
			// aapt resource value: 0x7f070001
			public const int green = 2131165185;
			
			// aapt resource value: 0x7f070019
			public const int greenButtonText = 2131165209;
			
			// aapt resource value: 0x7f07001d
			public const int lightBlueBackground = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int lightBlueBackground2 = 2131165214;
			
			// aapt resource value: 0x7f07000c
			public const int listEmptyText = 2131165196;
			
			// aapt resource value: 0x7f070011
			public const int localFilelistBackground = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int localListEmptyText = 2131165202;
			
			// aapt resource value: 0x7f070018
			public const int loginButtonText = 2131165208;
			
			// aapt resource value: 0x7f070015
			public const int loginText = 2131165205;
			
			// aapt resource value: 0x7f070020
			public const int mediumGrayText = 2131165216;
			
			// aapt resource value: 0x7f070029
			public const int passcodeBackgroundOverride = 2131165225;
			
			// aapt resource value: 0x7f07003e
			public const int passwordStrength1 = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public const int passwordStrength2 = 2131165247;
			
			// aapt resource value: 0x7f070040
			public const int passwordStrength3 = 2131165248;
			
			// aapt resource value: 0x7f070041
			public const int passwordStrength4 = 2131165249;
			
			// aapt resource value: 0x7f07003c
			public const int passwordStrengthMeterLit = 2131165244;
			
			// aapt resource value: 0x7f07003b
			public const int passwordStrengthMeterUnlit = 2131165243;
			
			// aapt resource value: 0x7f07003a
			public const int passwordStrengthText = 2131165242;
			
			// aapt resource value: 0x7f07003d
			public const int passwordStrengthUnlitPhone = 2131165245;
			
			// aapt resource value: 0x7f07002e
			public const int photoTabBackground = 2131165230;
			
			// aapt resource value: 0x7f070000
			public const int red = 2131165184;
			
			// aapt resource value: 0x7f07001a
			public const int redButtonText = 2131165210;
			
			// aapt resource value: 0x7f070017
			public const int ssLoginText = 2131165207;
			
			// aapt resource value: 0x7f070044
			public const int ss_passwordStrengthMeterLit = 2131165252;
			
			// aapt resource value: 0x7f070043
			public const int ss_passwordStrengthMeterUnlit = 2131165251;
			
			// aapt resource value: 0x7f070042
			public const int ss_passwordStrengthText = 2131165250;
			
			// aapt resource value: 0x7f070033
			public const int statusBarSeparator = 2131165235;
			
			// aapt resource value: 0x7f070014
			public const int text = 2131165204;
			
			// aapt resource value: 0x7f070007
			public const int textFieldStroke = 2131165191;
			
			// aapt resource value: 0x7f070013
			public const int textHighlight = 2131165203;
			
			// aapt resource value: 0x7f070026
			public const int titleBarText = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int titleBarTextWhite = 2131165223;
			
			// aapt resource value: 0x7f070025
			public const int tourBoxText = 2131165221;
			
			// aapt resource value: 0x7f070024
			public const int tourGrayBorder = 2131165220;
			
			// aapt resource value: 0x7f070022
			public const int tourText = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int tourTitleText = 2131165219;
			
			// aapt resource value: 0x7f070037
			public const int translucentBlackBackground = 2131165239;
			
			// aapt resource value: 0x7f070039
			public const int translucentFileListMediumGrayText = 2131165241;
			
			// aapt resource value: 0x7f070036
			public const int translucentWhiteBackground = 2131165238;
			
			// aapt resource value: 0x7f070038
			public const int translucentWhiteText = 2131165240;
			
			// aapt resource value: 0x7f070046
			public const int videoIconDetailsBackground = 2131165254;
			
			// aapt resource value: 0x7f070003
			public const int whiteBackground = 2131165187;
			
			// aapt resource value: 0x7f070030
			public const int whiteText = 2131165232;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f05000f
			public const int appStoreInterstitialMargin = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int buttonTextSize = 2131034126;
			
			// aapt resource value: 0x7f050000
			public const int dbx_action_bar_default_height = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int dbx_action_bar_icon_vertical_padding = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int dbx_action_bar_subtitle_bottom_margin = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int dbx_action_bar_subtitle_text_size = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int dbx_action_bar_subtitle_top_margin = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int dbx_action_bar_title_text_size = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int dbx_action_button_min_width = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int dbx_dialog_min_width_major = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int dbx_dialog_min_width_minor = 2131034125;
			
			// aapt resource value: 0x7f050009
			public const int dbx_dropdownitem_icon_width = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int dbx_dropdownitem_text_padding_left = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int dbx_dropdownitem_text_padding_right = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int dbx_search_view_preferred_width = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int dbx_search_view_text_min_width = 2131034122;
			
			// aapt resource value: 0x7f050011
			public const int fileChooserButtonLeft = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int fileChooserButtonRight = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int fileChooserButtonsPadding = 2131034128;
			
			// aapt resource value: 0x7f050016
			public const int fileChooserPaddingBottom = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int fileChooserPaddingLeft = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int fileChooserPaddingRight = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int fileChooserPaddingTop = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int fileChooserTitleText = 2131034135;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_bar_light_gray_bottom = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_btn_green_disabled = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_btn_green_focused = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_btn_green_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_btn_green_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_btn_light_gray_disabled = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_btn_light_gray_focused = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_btn_light_gray_normal = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_btn_light_gray_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_button_green = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_button_light_gray = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_launcher = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_new = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int monoandroidsplash = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int tab_dropbox = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int tab_dropbox_inactive = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090010
			public const int btnAdd = 2131296272;
			
			// aapt resource value: 0x7f090015
			public const int btnCreate = 2131296277;
			
			// aapt resource value: 0x7f090018
			public const int btnDirect = 2131296280;
			
			// aapt resource value: 0x7f090017
			public const int btnPreview = 2131296279;
			
			// aapt resource value: 0x7f09000a
			public const int dbx_bottom_bar = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int dbx_bottom_bar_cancel_button = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int dbx_bottom_bar_ok_button = 2131296268;
			
			// aapt resource value: 0x7f090009
			public const int dbx_bottom_space = 2131296265;
			
			// aapt resource value: 0x7f090001
			public const int dbx_button_bar = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int dbx_button_container = 2131296256;
			
			// aapt resource value: 0x7f090006
			public const int dbx_icon = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int dbx_install_main = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int dbx_install_sub = 2131296264;
			
			// aapt resource value: 0x7f090003
			public const int dbx_install_title = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int dbx_main_container = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int dbx_separator = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int dbx_top_space = 2131296261;
			
			// aapt resource value: 0x7f09000e
			public const int editTextAddress = 2131296270;
			
			// aapt resource value: 0x7f09000d
			public const int editTextName = 2131296269;
			
			// aapt resource value: 0x7f09000f
			public const int editTextNumber = 2131296271;
			
			// aapt resource value: 0x7f090013
			public const int lblSubtitle = 2131296275;
			
			// aapt resource value: 0x7f090012
			public const int lblTitle = 2131296274;
			
			// aapt resource value: 0x7f090014
			public const int listviewData = 2131296276;
			
			// aapt resource value: 0x7f090016
			public const int myButton = 2131296278;
			
			// aapt resource value: 0x7f090011
			public const int myImageView = 2131296273;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int dbx_max_action_buttons = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int app_store_interstitial = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int bottom_bar_light = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int bottom_buttons_light = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int build = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int imageLoad = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int infoview = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int list_item_entry = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int list_item_section = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int listview = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000c
			public const int app_name = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int btnCreate = 2130968587;
			
			// aapt resource value: 0x7f04000e
			public const int btnDirect = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int btnPreview = 2130968589;
			
			// aapt resource value: 0x7f040003
			public const int dbx_install = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int dbx_install_button_cancel = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int dbx_install_button_ok = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int dbx_install_main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int dbx_install_sub = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int dbx_update = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int dbx_update_button_ok = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int dbx_update_main = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int dbx_update_sub = 2130968583;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int pick_gallery = 2130968586;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int AppBaseTheme = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int AppTheme = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int BottomBar = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int BottomBarContainer = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int CommonButtonGreen = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int CommonButtonLightGray = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int Mono_Android_Theme_Splash = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int _CommonButtonBase = 2131230724;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
